# Generated by Django 5.2.5 on 2025-08-30 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('MDB_REPLY', 'MDB Replies'), ('TICKET_RESPONSE', 'Ticket Responses'), ('ASSIGNMENT_UPLOAD', 'Assignment Upload'), ('ASSIGNMENT_MARKING', 'Assignment Marking'), ('GDB_MARKING', 'GDB Marking'), ('SESSION_TRACKING', 'Session Tracking'), ('EMAIL_RESPONSE', 'Email Responses')], max_length=30)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict, help_text="e.g., {'topic': 'Week 1 Intro', 'count': 15}")),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_api.course')),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('ACTIVITY_SUMMARY', 'Activity Summary'), ('PERFORMANCE_ANALYSIS', 'Instructor Performance Analysis'), ('SYSTEM_USAGE', 'System Usage Report')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('USER_CREATED', 'User Account Created'), ('USER_UPDATED', 'User Account Updated'), ('USER_DELETED', 'User Account Deleted'), ('REPORT_GENERATED', 'Report Generated'), ('COURSE_CREATED', 'Course Created')], max_length=30)),
                ('details', models.JSONField(default=dict, help_text="Details of the event, e.g., {'username': 'johndoe'}")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
